substitutions:
  _REGION: us-central1
  _SERVICE: signing-bee
  _REPO: signing-bee

steps:
  - name: gcr.io/cloud-builders/docker
    args: [
      'build',
      '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$SHORT_SHA',
      '.'
    ]
  - name: gcr.io/cloud-builders/docker
    args: [
      'push',
      '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$SHORT_SHA'
    ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args: [
      'run', 'deploy', '$_SERVICE',
      '--image', '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$SHORT_SHA',
      '--region', '$_REGION',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$SHORT_SHA
